version: '3.8'
services:
  cadquery-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cadquery-app
    ports:
      - "5000:5000"
    volumes:
      - ./cadfiles/:/app
